name: initial-service-ci

on:
  pull_request:
    branches: [main]
    paths:
      - "initial-service/**"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest # change docker image to be closer to what we'll deploy with?

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Run UTs
        run: go test -cover ./...
        working-directory: initial-service
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      - name: Check for formatting issues
        run: test -z $(go fmt ./...)
        working-directory: initial-service
