name: initial-service-ci

on:
  pull_request:
    branches: [main]
    paths:
      - "initial-service/**"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest # change docker image to be closer to what we'll deploy with?

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Run UTs
        run: go test -cover ./...
        working-directory: initial-service
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Check commit messages
        run: |
          git fetch --prune --unshallow || true
          git fetch origin ${{ github.event.pull_request.base.ref }}
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          git log $BASE_BRANCH...${{ github.head_ref }} --pretty=format:"%s" | 
          grep -vE '^AGG-[0-9]+' | 
          grep -q . && exit 1 || exit 0 
        # fetch this branch, 
        # get the commit messages introduced by this branch (not in main branch)
        # check if they start with AGG-[0-9]+
        # exit 1 if at least one of them doesn't meet that criteria
      - name: Check for formatting issues
        run: test -z $(go fmt ./...)
        working-directory: initial-service
